<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <UserSecretsId>efcore-cdc-sample-worker</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Wallaby\Wallaby.csproj" />
    <ProjectReference Include="..\..\src\Wallaby.Providers.EntityFrameworkCore\Wallaby.Providers.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\src\Wallaby.Sinks.Meilisearch\Wallaby.Sinks.Meilisearch.csproj" />
  </ItemGroup>

</Project>
