<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Wallaby\Wallaby.csproj" />
    <ProjectReference Include="..\..\src\Wallaby.Sinks.Meilisearch\Wallaby.Sinks.Meilisearch.csproj" />
    <ProjectReference Include="..\Wallaby.TestModel\Wallaby.TestModel.csproj" />
    <ProjectReference Include="..\Wallaby.TestInfrastructure\Wallaby.TestInfrastructure.csproj" />
  </ItemGroup>

</Project>
