<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>Wallaby.Sinks.Meilisearch</PackageId>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Description>Meilisearch destination/sink for Wallaby: keep a Meilisearch index in sync with Postgres changes.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wallaby\Wallaby.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Wallaby.Sinks.Meilisearch.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotNet.ReproducibleBuilds">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Meilisearch" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>

  <Import Project="../../Package.Build.props" />
</Project>
