<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit.Core" />
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Wallaby\Wallaby.csproj" />
    <ProjectReference Include="..\..\src\Wallaby.Testing\Wallaby.Testing.csproj" />
    <ProjectReference Include="..\Wallaby.TestModel\Wallaby.TestModel.csproj" />
  </ItemGroup>

</Project>
