<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EFCore.CDC\EFCore.CDC.csproj" />
    <ProjectReference Include="..\..\src\EFCore.CDC.Meilisearch\EFCore.CDC.Meilisearch.csproj" />
    <ProjectReference Include="..\EFCore.CDC.TestModel\EFCore.CDC.TestModel.csproj" />
    <ProjectReference Include="..\EFCore.CDC.TestInfrastructure\EFCore.CDC.TestInfrastructure.csproj" />
  </ItemGroup>

</Project>
