<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit.Core" />
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EFCore.CDC\EFCore.CDC.csproj" />
    <ProjectReference Include="..\EFCore.CDC.TestModel\EFCore.CDC.TestModel.csproj" />
  </ItemGroup>

</Project>
