<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>EFCore.CDC.Meilisearch</PackageId>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Description>Meilisearch destination/sink for EFCore.CDC: keep a Meilisearch index in sync with Postgres changes.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EFCore.CDC\EFCore.CDC.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Meilisearch" />
  </ItemGroup>

</Project>
